[package]
name = "helper-macros"
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
# syn = { version = "1", features = ["full"] }
# quote = "1"
# proc-macro2 = "1"
